data <- c(12, 15, 18, 22, 25, 28, 32, 35)
cat("Data:", paste(data, collapse=", "), "\n")
mean_val <- mean(data)
cat("Mean:", mean_val, "\n")
variance <- sum((data - mean_val)^2) / length(data)
cat("Variance:", variance, "\n")
std_dev <- sqrt(variance)
cat("Standard deviation:", std_dev, "\n")
cat("Rounded to 2 decimals:", round(std_dev, 2), "\n")
